//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yinyue200.ClrSystem.Text.Encoding.CodePages.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yinyue200.Corefx.CodePages.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not a supported code page. 的本地化字符串。
        /// </summary>
        internal static string Argument_CodepageNotSupported {
            get {
                return ResourceManager.GetString("Argument_CodepageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder &apos;{0}&apos; fallback &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Argument_EncoderFallbackNotEmpty {
            get {
                return ResourceManager.GetString("Argument_EncoderFallbackNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output byte buffer is too small to contain the encoded data, encoding &apos;{0}&apos; fallback &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Argument_EncodingConversionOverflowBytes {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output char buffer is too small to contain the decoded characters, encoding &apos;{0}&apos; fallback &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Argument_EncodingConversionOverflowChars {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String contains invalid Unicode code points. 的本地化字符串。
        /// </summary>
        internal static string Argument_InvalidCharSequenceNoIndex {
            get {
                return ResourceManager.GetString("Argument_InvalidCharSequenceNoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recursive fallback not allowed for character \\u{0:X4}. 的本地化字符串。
        /// </summary>
        internal static string Argument_RecursiveFallback {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recursive fallback not allowed for bytes {0}. 的本地化字符串。
        /// </summary>
        internal static string Argument_RecursiveFallbackBytes {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallbackBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array cannot be null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_Array {
            get {
                return ResourceManager.GetString("ArgumentNull_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many characters. The resulting number of bytes is larger than what can be returned as an int. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_GetByteCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetByteCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many bytes. The resulting number of chars is larger than what can be returned as an int. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_GetCharCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetCharCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index was out of range. Must be non-negative and less than the size of the collection. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index and count must refer to a location within the string. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCount {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index and count must refer to a location within the buffer. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCountBuffer {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCountBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-negative number required. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid values are between {0} and {1}, inclusive. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange_Range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Western European (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10000 {
            get {
                return ResourceManager.GetString("Globalization_cp_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10001 {
            get {
                return ResourceManager.GetString("Globalization_cp_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Traditional (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10002 {
            get {
                return ResourceManager.GetString("Globalization_cp_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10003 {
            get {
                return ResourceManager.GetString("Globalization_cp_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10004 {
            get {
                return ResourceManager.GetString("Globalization_cp_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10005 {
            get {
                return ResourceManager.GetString("Globalization_cp_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greek (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10006 {
            get {
                return ResourceManager.GetString("Globalization_cp_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyrillic (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10007 {
            get {
                return ResourceManager.GetString("Globalization_cp_10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Simplified (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10008 {
            get {
                return ResourceManager.GetString("Globalization_cp_10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Romanian (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10010 {
            get {
                return ResourceManager.GetString("Globalization_cp_10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ukrainian (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10017 {
            get {
                return ResourceManager.GetString("Globalization_cp_10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thai (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10021 {
            get {
                return ResourceManager.GetString("Globalization_cp_10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Central European (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10029 {
            get {
                return ResourceManager.GetString("Globalization_cp_10029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icelandic (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10079 {
            get {
                return ResourceManager.GetString("Globalization_cp_10079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turkish (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10081 {
            get {
                return ResourceManager.GetString("Globalization_cp_10081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Croatian (Mac) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_10082 {
            get {
                return ResourceManager.GetString("Globalization_cp_10082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Turkish Latin-5) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1026 {
            get {
                return ResourceManager.GetString("Globalization_cp_1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM Latin-1 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1047 {
            get {
                return ResourceManager.GetString("Globalization_cp_1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (US-Canada-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1140 {
            get {
                return ResourceManager.GetString("Globalization_cp_1140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Germany-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1141 {
            get {
                return ResourceManager.GetString("Globalization_cp_1141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Denmark-Norway-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1142 {
            get {
                return ResourceManager.GetString("Globalization_cp_1142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Finland-Sweden-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1143 {
            get {
                return ResourceManager.GetString("Globalization_cp_1143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Italy-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1144 {
            get {
                return ResourceManager.GetString("Globalization_cp_1144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Spain-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1145 {
            get {
                return ResourceManager.GetString("Globalization_cp_1145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (UK-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1146 {
            get {
                return ResourceManager.GetString("Globalization_cp_1146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (France-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1147 {
            get {
                return ResourceManager.GetString("Globalization_cp_1147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (International-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1148 {
            get {
                return ResourceManager.GetString("Globalization_cp_1148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Icelandic-Euro) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1149 {
            get {
                return ResourceManager.GetString("Globalization_cp_1149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Central European (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1250 {
            get {
                return ResourceManager.GetString("Globalization_cp_1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyrillic (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1251 {
            get {
                return ResourceManager.GetString("Globalization_cp_1251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Western European (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1252 {
            get {
                return ResourceManager.GetString("Globalization_cp_1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greek (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1253 {
            get {
                return ResourceManager.GetString("Globalization_cp_1253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turkish (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1254 {
            get {
                return ResourceManager.GetString("Globalization_cp_1254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1255 {
            get {
                return ResourceManager.GetString("Globalization_cp_1255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1256 {
            get {
                return ResourceManager.GetString("Globalization_cp_1256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baltic (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1257 {
            get {
                return ResourceManager.GetString("Globalization_cp_1257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vietnamese (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1258 {
            get {
                return ResourceManager.GetString("Globalization_cp_1258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean (Johab) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_1361 {
            get {
                return ResourceManager.GetString("Globalization_cp_1361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Traditional (CNS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20000 {
            get {
                return ResourceManager.GetString("Globalization_cp_20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCA Taiwan 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20001 {
            get {
                return ResourceManager.GetString("Globalization_cp_20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Traditional (Eten) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20002 {
            get {
                return ResourceManager.GetString("Globalization_cp_20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM5550 Taiwan 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20003 {
            get {
                return ResourceManager.GetString("Globalization_cp_20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TeleText Taiwan 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20004 {
            get {
                return ResourceManager.GetString("Globalization_cp_20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wang Taiwan 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20005 {
            get {
                return ResourceManager.GetString("Globalization_cp_20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Western European (IA5) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20105 {
            get {
                return ResourceManager.GetString("Globalization_cp_20105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German (IA5) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20106 {
            get {
                return ResourceManager.GetString("Globalization_cp_20106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swedish (IA5) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20107 {
            get {
                return ResourceManager.GetString("Globalization_cp_20107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Norwegian (IA5) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20108 {
            get {
                return ResourceManager.GetString("Globalization_cp_20108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T.61 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20261 {
            get {
                return ResourceManager.GetString("Globalization_cp_20261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO-6937 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20269 {
            get {
                return ResourceManager.GetString("Globalization_cp_20269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Germany) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20273 {
            get {
                return ResourceManager.GetString("Globalization_cp_20273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Denmark-Norway) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20277 {
            get {
                return ResourceManager.GetString("Globalization_cp_20277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Finland-Sweden) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20278 {
            get {
                return ResourceManager.GetString("Globalization_cp_20278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Italy) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20280 {
            get {
                return ResourceManager.GetString("Globalization_cp_20280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Spain) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20284 {
            get {
                return ResourceManager.GetString("Globalization_cp_20284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (UK) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20285 {
            get {
                return ResourceManager.GetString("Globalization_cp_20285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Japanese katakana) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20290 {
            get {
                return ResourceManager.GetString("Globalization_cp_20290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (France) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20297 {
            get {
                return ResourceManager.GetString("Globalization_cp_20297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Arabic) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20420 {
            get {
                return ResourceManager.GetString("Globalization_cp_20420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Greek) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20423 {
            get {
                return ResourceManager.GetString("Globalization_cp_20423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Hebrew) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20424 {
            get {
                return ResourceManager.GetString("Globalization_cp_20424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Korean Extended) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20833 {
            get {
                return ResourceManager.GetString("Globalization_cp_20833", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Thai) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20838 {
            get {
                return ResourceManager.GetString("Globalization_cp_20838", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyrillic (KOI8-R) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20866 {
            get {
                return ResourceManager.GetString("Globalization_cp_20866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Icelandic) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20871 {
            get {
                return ResourceManager.GetString("Globalization_cp_20871", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Cyrillic Russian) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20880 {
            get {
                return ResourceManager.GetString("Globalization_cp_20880", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Turkish) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20905 {
            get {
                return ResourceManager.GetString("Globalization_cp_20905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM Latin-1 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20924 {
            get {
                return ResourceManager.GetString("Globalization_cp_20924", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese (JIS 0208-1990 and 0212-1990) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20932 {
            get {
                return ResourceManager.GetString("Globalization_cp_20932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Simplified (GB2312-80) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20936 {
            get {
                return ResourceManager.GetString("Globalization_cp_20936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean Wansung 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_20949 {
            get {
                return ResourceManager.GetString("Globalization_cp_20949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Cyrillic Serbian-Bulgarian) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_21025 {
            get {
                return ResourceManager.GetString("Globalization_cp_21025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ext Alpha Lowercase 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_21027 {
            get {
                return ResourceManager.GetString("Globalization_cp_21027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyrillic (KOI8-U) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_21866 {
            get {
                return ResourceManager.GetString("Globalization_cp_21866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Central European (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28592 {
            get {
                return ResourceManager.GetString("Globalization_cp_28592", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latin 3 (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28593 {
            get {
                return ResourceManager.GetString("Globalization_cp_28593", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baltic (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28594 {
            get {
                return ResourceManager.GetString("Globalization_cp_28594", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyrillic (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28595 {
            get {
                return ResourceManager.GetString("Globalization_cp_28595", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28596 {
            get {
                return ResourceManager.GetString("Globalization_cp_28596", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greek (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28597 {
            get {
                return ResourceManager.GetString("Globalization_cp_28597", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew (ISO-Visual) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28598 {
            get {
                return ResourceManager.GetString("Globalization_cp_28598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turkish (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28599 {
            get {
                return ResourceManager.GetString("Globalization_cp_28599", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estonian (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28603 {
            get {
                return ResourceManager.GetString("Globalization_cp_28603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latin 9 (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_28605 {
            get {
                return ResourceManager.GetString("Globalization_cp_28605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Europa 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_29001 {
            get {
                return ResourceManager.GetString("Globalization_cp_29001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (US-Canada) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_37 {
            get {
                return ResourceManager.GetString("Globalization_cp_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew (ISO-Logical) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_38598 {
            get {
                return ResourceManager.GetString("Globalization_cp_38598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OEM United States 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_437 {
            get {
                return ResourceManager.GetString("Globalization_cp_437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (International) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_500 {
            get {
                return ResourceManager.GetString("Globalization_cp_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Defined 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50000 {
            get {
                return ResourceManager.GetString("Globalization_cp_50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese (JIS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50220 {
            get {
                return ResourceManager.GetString("Globalization_cp_50220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese (JIS-Allow 1 byte Kana) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50221 {
            get {
                return ResourceManager.GetString("Globalization_cp_50221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese (JIS-Allow 1 byte Kana - SO/SI) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50222 {
            get {
                return ResourceManager.GetString("Globalization_cp_50222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean (ISO) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50225 {
            get {
                return ResourceManager.GetString("Globalization_cp_50225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Simplified (ISO-2022) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50227 {
            get {
                return ResourceManager.GetString("Globalization_cp_50227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Traditional (ISO-2022) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50229 {
            get {
                return ResourceManager.GetString("Globalization_cp_50229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Japanese and Japanese Katakana) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50930 {
            get {
                return ResourceManager.GetString("Globalization_cp_50930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Japanese and US-Canada) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50931 {
            get {
                return ResourceManager.GetString("Globalization_cp_50931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Korean and Korean Extended) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50933 {
            get {
                return ResourceManager.GetString("Globalization_cp_50933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Simplified Chinese) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50935 {
            get {
                return ResourceManager.GetString("Globalization_cp_50935", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Traditional Chinese) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50937 {
            get {
                return ResourceManager.GetString("Globalization_cp_50937", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Japanese and Japanese-Latin) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_50939 {
            get {
                return ResourceManager.GetString("Globalization_cp_50939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese (EUC) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_51932 {
            get {
                return ResourceManager.GetString("Globalization_cp_51932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Simplified (EUC) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_51936 {
            get {
                return ResourceManager.GetString("Globalization_cp_51936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean (EUC) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_51949 {
            get {
                return ResourceManager.GetString("Globalization_cp_51949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Simplified (HZ) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_52936 {
            get {
                return ResourceManager.GetString("Globalization_cp_52936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Simplified (GB18030) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_54936 {
            get {
                return ResourceManager.GetString("Globalization_cp_54936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Devanagari 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57002 {
            get {
                return ResourceManager.GetString("Globalization_cp_57002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Bengali 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57003 {
            get {
                return ResourceManager.GetString("Globalization_cp_57003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Tamil 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57004 {
            get {
                return ResourceManager.GetString("Globalization_cp_57004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Telugu 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57005 {
            get {
                return ResourceManager.GetString("Globalization_cp_57005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Assamese 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57006 {
            get {
                return ResourceManager.GetString("Globalization_cp_57006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Oriya 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57007 {
            get {
                return ResourceManager.GetString("Globalization_cp_57007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Kannada 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57008 {
            get {
                return ResourceManager.GetString("Globalization_cp_57008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Malayalam 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57009 {
            get {
                return ResourceManager.GetString("Globalization_cp_57009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Gujarati 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57010 {
            get {
                return ResourceManager.GetString("Globalization_cp_57010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISCII Punjabi 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_57011 {
            get {
                return ResourceManager.GetString("Globalization_cp_57011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic (ASMO 708) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_708 {
            get {
                return ResourceManager.GetString("Globalization_cp_708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_720 {
            get {
                return ResourceManager.GetString("Globalization_cp_720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greek (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_737 {
            get {
                return ResourceManager.GetString("Globalization_cp_737", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baltic (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_775 {
            get {
                return ResourceManager.GetString("Globalization_cp_775", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Western European (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_850 {
            get {
                return ResourceManager.GetString("Globalization_cp_850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Central European (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_852 {
            get {
                return ResourceManager.GetString("Globalization_cp_852", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OEM Cyrillic 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_855 {
            get {
                return ResourceManager.GetString("Globalization_cp_855", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turkish (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_857 {
            get {
                return ResourceManager.GetString("Globalization_cp_857", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OEM Multilingual Latin I 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_858 {
            get {
                return ResourceManager.GetString("Globalization_cp_858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portuguese (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_860 {
            get {
                return ResourceManager.GetString("Globalization_cp_860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icelandic (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_861 {
            get {
                return ResourceManager.GetString("Globalization_cp_861", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_862 {
            get {
                return ResourceManager.GetString("Globalization_cp_862", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French Canadian (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_863 {
            get {
                return ResourceManager.GetString("Globalization_cp_863", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic (864) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_864 {
            get {
                return ResourceManager.GetString("Globalization_cp_864", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nordic (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_865 {
            get {
                return ResourceManager.GetString("Globalization_cp_865", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyrillic (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_866 {
            get {
                return ResourceManager.GetString("Globalization_cp_866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greek, Modern (DOS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_869 {
            get {
                return ResourceManager.GetString("Globalization_cp_869", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Multilingual Latin-2) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_870 {
            get {
                return ResourceManager.GetString("Globalization_cp_870", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thai (Windows) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_874 {
            get {
                return ResourceManager.GetString("Globalization_cp_874", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM EBCDIC (Greek Modern) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_875 {
            get {
                return ResourceManager.GetString("Globalization_cp_875", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese (Shift-JIS) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_932 {
            get {
                return ResourceManager.GetString("Globalization_cp_932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Simplified (GB2312) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_936 {
            get {
                return ResourceManager.GetString("Globalization_cp_936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_949 {
            get {
                return ResourceManager.GetString("Globalization_cp_949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Traditional (Big5) 的本地化字符串。
        /// </summary>
        internal static string Globalization_cp_950 {
            get {
                return ResourceManager.GetString("Globalization_cp_950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find a resource entry for the encoding codepage &apos;{0} - {1}&apos; 的本地化字符串。
        /// </summary>
        internal static string MissingEncodingNameResource {
            get {
                return ResourceManager.GetString("MissingEncodingNameResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data is available for encoding {0}. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_NoCodepageData {
            get {
                return ResourceManager.GetString("NotSupported_NoCodepageData", resourceCulture);
            }
        }
    }
}
